# @import ./auth.http

###
# @ref auth
GET http://localhost:5000/api/user/stat
Authorization: Bearer {{ auth.accessToken }}
###
# @ref auth
GET http://localhost:5000/api/user/stat/words
Authorization: Bearer {{ auth.accessToken }}


###
# @ref auth
GET http://localhost:5000/api/user/stat/topics?offset_days=0
Authorization: Bearer {{ auth.accessToken }}


###
# @ref auth
PUT http://localhost:5000/api/user/stat
Authorization: Bearer {{ auth.accessToken }}
Content-Type: application/json

{
    "success": [],
    "failed": []
}
