# @import ./auth.http

###
# @ref auth
GET http://localhost:5000/api/user
Authorization: Bearer {{ auth.access_token }}

###
# @ref auth
GET http://localhost:5000/api/user/progress
Authorization: Bearer {{ auth.access_token }}

###
# @ref auth
GET http://localhost:5000/api/user/stat
Authorization: Bearer {{ auth.access_token }}
###
# @ref auth
GET http://localhost:5000/api/user/troubles
Authorization: Bearer {{ auth.access_token }}


###
# @ref auth
GET http://localhost:5000/api/user/rating?days=20
Authorization: Bearer {{ auth.access_token }}

###
# @ref auth
PUT http://localhost:5000/api/user/stat
Authorization: Bearer {{ auth.access_token }}
Content-Type: application/json

{
    "success": [],
    "failed": []
}

###
# @ref auth
PUT http://localhost:5000/api/user/report
Authorization: Bearer {{ auth.access_token }}
Content-Type: application/json

{ "word": 1}


###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{"login": "megatron_1981", "password": "12", "invite": "rrrrr"}
