# @import ./auth.http

###
# @ref auth
GET http://localhost:5000/api/user
Authorization: Bearer {{ auth.access_token }}

###
# @ref auth
GET http://localhost:5000/api/user/stat
Authorization: Bearer {{ auth.access_token }}

###
# @ref auth
PUT http://localhost:5000/api/user/stat
Authorization: Bearer {{ auth.access_token }}
{
    "success": [],
    "failed": []
}