###
POST http://localhost:5000/api/auth/token
Content-Type: application/json

{"login":"default", "password": ""}

GET http://localhost:5000/api/user

###
GET http://localhost:5000/api/user/stat

PUT http://localhost:5000/api/user/stat
Content-Type: application/json

{
    "success": [],
    "failed": []
}